---
- name: 'Enable EPEL Repository'
  yum:
    name: 'epel-release'
    state: 'present'
  become: true
  when:
    - fail2ban_repo_enable | bool

- name: 'Install fail2ban packages'
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ fail2ban_packages }}"
  notify:
    - 'HANDLER | Restart fail2ban'

- name: 'Enable autorestart fail2ban'
  service:
    name: 'fail2ban'
    enabled: 'True'

- name: 'CONFIG | Include configuration tasks'
  become: true
  include: "{{ role_path }}/tasks/manage_config.yml"

- name: 'SERVICE | Include services tasks'
  become: true
  include: "{{ role_path }}/tasks/manage_service.yml"

- name: 'Copy http-get-dos file'
  copy:
    src: 'http-get-dos.conf'
    dest: '/etc/fail2ban/filter.d'
    mode: '0644'
  notify:
    - 'HANDLER | Restart fail2ban'
